development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: event_dev
  pool: 5
  username: root
  password: root

test: &test
  <<: *development
production:
  <<: *development
